kernel:
  image: linuxkit/kernel:4.14.52
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0 console=ttysclp0"
init:
  - linuxkit/init:v0.6
  - linuxkit/runc:v0.6
  - linuxkit/containerd:v0.6
  - linuxkit/ca-certificates:v0.6
onboot:
  - name: rngd1
    image: linuxkit/rngd:v0.6
    command: ["/sbin/rngd", "-1"]
  - name: sysctl
    image: linuxkit/sysctl:v0.6
  - name: dhcpcd
    image: linuxkit/dhcpcd:v0.6
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  - name: metadata
    image: linuxkit/metadata:v0.6
  - name: nat
    image: linuxkit/ip:v0.6
    binds: ["/etc/nat.sh:/etc/nat.sh"]
    command: ["/etc/nat.sh"]
  - name: wg0
    image: linuxkit/ip:v0.6
    binds: ["/etc/wireguard:/etc/wireguard"]
    command: ["/usr/bin/lk-wg-config", "configure", "/etc/wireguard/wg0.conf"]
    runtime:
      interfaces:
        - name: wg0
          add: wireguard
          createInRoot: true
services:
  - name: rngd
    image: linuxkit/rngd:v0.6
  - name: strongswan
    image: saljam/strongswan:5d6a176d693a9125d26529573b898047f423b11e
    binds:
      - /etc/resolv.conf:/etc/resolv.conf
      - /etc/ipsec.conf:/etc/ipsec.conf
      - /etc/strongswan.conf:/etc/strongswan.conf
      - /etc/ipsec.secrets:/etc/ipsec.secrets
    #  - /run/config/strongswan/ipsec.secrets:/etc/ipsec.secrets
  - name: sshd
    image: linuxkit/sshd:v0.6
    #binds:
    #  - /run/config/ssh/authorized_keys:/root/.ssh/authorized_keys
  - name: iodine
    image: saljam/iodine:b1e79962e9a13e968413e08368df5c630af0cab0
    binds:
      - /etc/iodine.sh:/etc/iodine.sh
      - /dev/net:/dev/net
    command: ["/etc/iodine.sh"]
files:
  - path: etc/nat.sh
    mode: "0555"
    contents: |
      #!/bin/sh
      iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
      iptables -A FORWARD -j ACCEPT
      sysctl net.ipv4.ip_forward=1
  - path: etc/ipsec.conf
    contents: |
      config setup
      conn %default
          left=%defaultroute
          ikelifetime=60m
          keylife=20m
          rekeymargin=3m
          keyingtries=1
          keyexchange=ikev2
          authby=secret
      conn c
          leftsubnet=0.0.0.0/0
          leftfirewall=yes
          right=%any
          rightsourceip=10.8.8.0/16
          auto=add
  # TODO get rid of this? set dns globally?
  - path: etc/strongswan.conf
    contents: |
      charon {
          load_modular = yes
          plugins {
              include strongswan.d/charon/*.conf
              attr {
                  dns = 1.1.1.1, 1.0.0.1, 8.8.8.8, 8.8.4.4
              }
          }
      }
      include strongswan.d/*.conf
  # TODO move the rest to user-data
  - path: etc/iodine.sh
    mode: "0555"
    contents: |
      #!/bin/sh
      exec /bin/iodined -f -P somepassword -c 10.24.24.1 d.0f.io
      sysctl net.ipv4.ip_forward=1
  - path: etc/ipsec.secrets
    contents: |
      : PSK CHANGEME
  - path: etc/wireguard/wg0.conf
    contents: |
      [Interface]
      PrivateKey = CHANGEME
      Address = 10.16.16.1/32
      ListenPort = 12915
      [Peer]
      PublicKey = CHANGEME
      AllowedIPs = 10.16.16.2/32
  - path: root/.ssh/authorized_keys
    mode: "0600"
    contents: |
      CHANGEME
