#!/bin/bash
set -e

name="${1:-linuxkit}"
dir="$(mktemp -d)"
trap "rm -rf $dir" EXIT

linuxkit pkg build -org saljam ./strongswan
linuxkit pkg build -org saljam ./iodine
linuxkit build -format raw-bios -dir $dir ./$name.yaml
mv "$dir/$name-bios.img" "$HOME/Desktop/tunnel-$(date -u +%Y%m%d%H%M%S).img"
